version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: Rachai
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - rachai-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rachai-backend
    volumes:
      - ./manifests:/etc/puppetlabs/code/environments/production/manifests
      - ./modules:/etc/puppetlabs/code/environments/production/modules
    ports:
      - "8081:8081"
    entrypoint: ["tail", "-f", "/dev/null"]
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://admin:adminpassword@mongodb:27017/Rachai?authSource=admin
    networks:
      - rachai-network

  nagios:
    image: jasonrivers/nagios:latest
    container_name: nagios
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nagios/etc:/opt/nagios/etc
      - ./nagios/var:/opt/nagios/var
    environment:
      NAGIOS_FQDN: nagios.local
    depends_on:
      - mongodb
      - app
    networks:
      - rachai-network

volumes:
  mongo-data:

networks:
  rachai-network:
    driver: bridge